## 1.Arithmetic Operators

In [1]:
# Input the numbers
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))

# sum
sum_result = num1 + num2

# difference
diff_result = num1 - num2

# product
prod_result = num1 * num2

# quotient
quot_result = num1 / num2

# Print the results
print("Sum:", sum_result)
print("Difference:", diff_result)
print("Product:", prod_result)
print("Quotient:", quot_result)

Enter the first number:  12
Enter the second number:  -15

Sum: -3.0
Difference: 27.0
Product: -180.0
Quotient: -0.8

## 2. Comparison Operators

In [2]:
# Input the numbers
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))

# Compare the numbers
if num1 > num2:
    print(num1, "is greater than", num2)
elif num1 < num2:
    print(num1, "is less than", num2)
else:
    print(num1, "is equal to", num2)

Enter the first number:  12
Enter the second number:  15

12.0 is less than 15.0

## 3. Assignment Operators

In [7]:
# Input the initial value
initial_value = float(input("Enter the initial value: "))

# Apply different assignment operators
initial_value += 5  # Add 5 to the initial value
print("After += 5, the value is:", initial_value)

initial_value -= 3  # Subtract 3 from the current value
print("After -= 3, the value is:", initial_value)

initial_value *= 2  # Multiply the current value by 2
print("After *= 2, the value is:", initial_value)

initial_value /= 4  # Divide the current value by 4
print("After /= 4, the value is:", initial_value)

initial_value **= 3  # Raise the current value to the power of 3
print("After **= 3, the value is:", initial_value)

initial_value //= 2  # Perform floor division of the current value by 2
print("After //= 2, the value is:", initial_value)

initial_value %= 3  # Take the modulus of the current value by 3
print("After %= 3, the value is:", initial_value)

Enter the initial value:  6

After += 5, the value is: 11.0
After -= 3, the value is: 8.0
After *= 2, the value is: 16.0
After /= 4, the value is: 4.0
After **= 3, the value is: 64.0
After //= 2, the value is: 32.0
After %= 3, the value is: 2.0

## 4. Comparison Operators

In [8]:
# Input the age
age = int(input("Enter your age: "))

# Check eligibility to vote
if age >= 18:
    print("You are eligible to vote!")
else:
    print("You are not eligible to vote yet.")

Enter your age:  15

You are not eligible to vote yet.

## 5. If-else Statements

In [9]:
# Input the number
number = float(input("Enter a number: "))

# Check if the number is positive, negative, or zero
if number > 0:
    print("The number is positive.")
elif number < 0:
    print("The number is negative.")
else:
    print("The number is zero.")

Enter a number:  10

The number is positive.

## 6. For Loops

In [10]:
# Input the string
input_string = input("Enter a string: ")

# Print each character on a separate line
for character in input_string:
    print(character)

Enter a string:  Hamed

H
a
m
e
d

## 7. While Loops

In [11]:
# Input the number
number = int(input("Enter a number: "))

# Initialize a counter
counter = 0

# Print even numbers up to the input number
while counter <= number:
    if counter % 2 == 0:
        print(counter)
    counter += 1

Enter a number:  15

0
2
4
6
8
10
12
14

## 8. Control Flow with Lists and Conditions

In [12]:
# Input the list of words
words = input("Enter a list of words, separated by spaces: ").split()

for word in words:
    if word.startswith('a') or word.startswith('A'):
        print("Length of", word, ":", len(word))

Enter a list of words, separated by spaces:  ahmad taghi hasan Arash Armita ahan

Length of ahmad : 5
Length of Arash : 5
Length of Armita : 6
Length of ahan : 4

## 9. Basic List Operations

In [13]:
# first list
list1 = [1, 2, 3, 4, 5]

# second list
list2 = [6, 7, 8, 9, 10]

# Concatenate the two lists
concatenated_list = list1 + list2

print("Concatenated List:", concatenated_list)

Concatenated List: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

## 10. Accessing List Elements

In [14]:
numbers = [10, 20, 30, 40, 50]

sum_of_elements = numbers[0] + numbers[-1]

print("Sum of the first and last elements:", sum_of_elements)

Sum of the first and last elements: 60

## 11. Modifying Lists

In [15]:
# list of numbers
numbers = [10, 20, 30, 40, 50]

# Change the value of the third element
numbers[2] = 35

print("Updated list of numbers:", numbers)

Updated list of numbers: [10, 20, 35, 40, 50]

## 12. Slicing and Sublists

In [16]:

strings = ["apple", "banana", "cherry", "date", "elderberry"]

# Create a sublist containing the last two elements
sublist = strings[-2:]

print("Sublist containing the last two elements:", sublist)

Sublist containing the last two elements: ['date', 'elderberry']

## 13. Basic Tuple Operations

In [19]:
my_tuple = ("apple", "banana", "cherry", "date", "elderberry")

# method 1
print("method 1\n")
for element in reversed(my_tuple):
    print(element)

# method 2
print("\n\nmethod 2\n")
for element in my_tuple[::-1]:
    print(element)

method 1

elderberry
date
cherry
banana
apple


method 2

elderberry
date
cherry
banana
apple

## 14. Accessing Tuple Elements

In [20]:
my_tuple = (10, 20, 30, 40, 50)

sum_of_elements = my_tuple[0] + my_tuple[-1]

print("Sum of the first and last elements:", sum_of_elements)

Sum of the first and last elements: 60

## 15. Modifying Tuples

In [21]:
# tuple of numbers
my_tuple = (10, 20, 30, 40, 50)

# Convert the tuple to a list
my_list = list(my_tuple)

# Change the value of the third element
my_list[2] = 35

# Convert the list back to a tuple
my_tuple = tuple(my_list)

# Print the updated tuple
print("Updated tuple of numbers:", my_tuple)

Updated tuple of numbers: (10, 20, 35, 40, 50)

## 16. Slicing and Subtuples

In [22]:
# tuple of strings
my_tuple = ("apple", "banana", "cherry", "date", "elderberry")

# subtuple containing the last two elements
subtuple = my_tuple[-2:]

# Print the subtuple
print("Subtuple containing the last two elements:", subtuple)

Subtuple containing the last two elements: ('date', 'elderberry')

## 17. Basic Dictionary Operations

In [23]:
# product dictionary
product = {
    "name": "Laptop",
    "price": 999.99,
    "quantity": 5
}

# Print the dictionary
print("Product dictionary:", product)

Product dictionary: {'name': 'Laptop', 'price': 999.99, 'quantity': 5}

## 18. Accessing Dictionary Elements

In [24]:
# person dictionary
person = {
    "name": "Hamed Daneshvar",
    "age": 26,
    "occupation": "Software Engineer"
}

# Print the value associated with the "name" key
print("Person's name:", person["name"])

Person's name: Hamed Daneshvar

## 19. Modifying Dictionaries

In [25]:
# product dictionary
product = {
    "name": "Laptop",
    "price": 999.99,
    "quantity": 5
}

# Update the value associated with the "quantity" key
product["quantity"] = 10

# Print the updated dictionary
print("Updated product dictionary:", product)

Updated product dictionary: {'name': 'Laptop', 'price': 999.99, 'quantity': 10}

## 20. Adding and Removing Dictionary Entries

In [26]:
# empty dictionary
person = {}

# Add key-value pairs for "name" and "age"
person["name"] = "Hamed Daneshvar"
person["age"] = 26

# Print the dictionary
print("Person dictionary:", person)

Person dictionary: {'name': 'Hamed Daneshvar', 'age': 26}

## 21. Creating and Modifying Sets

In [37]:
# set with tuple product information
product_set = {("Laptop", 5), ("vacuum", 2)}

# Create a new empty set to store updated product information
new_product_set = set()

for product in product_set:
    name, quantity = product
    
    # Check if the product name is "Laptop"
    if name == "Laptop":
        quantity += 5
        product = name, quantity
        
    # Add the product tuple to the new set
    new_product_set.add(product)

# Print the updated product set
print(new_product_set)

{('vacuum', 2), ('Laptop', 10)}

## 22. Set Operations

In [38]:
# Create two sets of numbers
set1 = {1, 2, 3, 4}
set2 = {3, 4, 5, 6}

# Perform union operation to combine them
union_set = set1.union(set2)

# Print the resulting set
print("Union set:", union_set)

Union set: {1, 2, 3, 4, 5, 6}

## 23. Removing Set Elements

### a section

In [41]:
# set of numbers
number_set = {1, 2, 3, 4, 5}

# Remove a specific element using the remove() method
number_set.remove(3)

# Print the updated set
print("Updated set:", number_set)

Updated set: {1, 2, 4, 5}

### b section

In [42]:
# set of strings
string_set = {"apple", "banana", "orange", "grape"}

# Remove an element using the discard() method
string_set.discard("orange")

# Print the updated set
print("Updated set:", string_set)

Updated set: {'grape', 'banana', 'apple'}

## 24. String Operations

In [43]:
my_string = "Hello!"

# Repeat the string multiple times using the multiplication operator
repeated_string = my_string * 3

# Print the repeated string
print("Repeated string:", repeated_string)

Repeated string: Hello!Hello!Hello!

## 25. Accessing String Characters

In [44]:
my_string = "Hello, World!"

# Print the last character
print("Last character:", my_string[-1])

Last character: !

## 26. String Length and Slicing

In [48]:
my_string = "Hello, World!"

# Print the substring
print("Substring:", my_string[3:-2])

Substring: lo, Worl

## 27. Modifying Strings

In [49]:
my_string = "Hello, World!"

# Print the uppercase string
print("Uppercase string:", my_string.upper())

Uppercase string: HELLO, WORLD!

## 28. Function Basics

In [51]:
def calculate_area(length, width):
    area = length * width
    return area

# Print the result
print("Area:", calculate_area(5, 3))

Area: 15

## 29. Function Parameters and Arguments

In [52]:
def add_numbers(num1, num2):
    sum = num1 + num2
    return sum

# Print the result
print("Sum:", add_numbers(5, 3))

Sum: 8

## 30. Default Parameters

In [53]:
def calculate_power(number, exponent=2):
    power = number ** exponent
    return power

# Print the result
print("Power:", calculate_power(3, 4))

Power: 81

## 31. Lambda Functions

In [54]:
is_divisible_by_2 = lambda number: number % 2 == 0

# Check if the number 6 is divisible by 2
result = is_divisible_by_2(6)
print(result)  # Output: True

# Check if the number 9 is divisible by 2
result = is_divisible_by_2(9)
print(result)  # Output: False

True
False

## 32. Sum of List

In [55]:
def calculate_sum(numbers):
    total = 0
    for number in numbers:
        total += number

    return total


numbers = [1, 2, 3, 4, 5]
print("Sum:", calculate_sum(numbers))

Sum: 15

## 33. Factorial

In [56]:
def calculate_factorial(number):
    factorial = 1
    for i in range(1, number + 1):
        factorial *= i

    return factorial


# Print the result
print("Factorial:", calculate_factorial(5))

Factorial: 120

## 34. Counting Vowels

In [57]:
def count_vowels(input_string):
    vowel_count = 0
    for char in input_string.lower():
        if char in 'aeiou':
            vowel_count += 1

    return vowel_count


input_string = "Hello World"
print("Number of vowels:", count_vowels(input_string))

Number of vowels: 3

## 35. Fibonacci Sequence

In [76]:
def print_fibonacci_sequence(number):
    first = 0
    second = 1

    if number >= first:
        print(first)
    if number >= second:
        print(second)

    while (first + second) <= number:
        next_number = first + second
        print(next_number)
        
        first = second
        second = next_number


print("Fibonacci sequence:")
print_fibonacci_sequence(15)

Fibonacci sequence:
0
1
1
2
3
5
8
13

## 36. Factorial

In [75]:
def calculate_factorial(number):
    if number == 0:
        return 1

    return number * calculate_factorial(number - 1)

# Print the result
print("Factorial:", calculate_factorial(5))

Factorial: 120

## 37. Fibonacci Sequence

In [79]:
def fibonacci(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1

    return fibonacci(n-1) + fibonacci(n-2)

# Print the result
print("Fibonacci sequence:", fibonacci(6))

Fibonacci sequence: 8

## 38. Divide by Zero

In [80]:
def divide_numbers(a, b):
    try:
        print("Result:", a / b)
    except ZeroDivisionError:
        print("Error: Division by zero is not allowed.")


num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))
divide_numbers(num1, num2)

Enter the first number:  5
Enter the second number:  0

Error: Division by zero is not allowed.

## 39. File Reading

In [82]:
def read_file(file_name):
    try:
        with open(file_name, 'r') as file:
            contents = file.read()
            print("File Contents:\n", contents)
    except FileNotFoundError:
        print("Error: File not found.")

file_name = input("Enter the file name: ")
read_file(file_name)

Enter the file name:  '.ipynb_checkpoints/FFCVS_Dec23_Course_Ex_silver_Python_Hamed_Daneshvar-checkpoint'

Error: File not found.

## 40. Input Validation

In [83]:
def get_positive_integer():
    while True:
        try:
            number = int(input("Enter a positive integer: "))
            if number <= 0:
                raise ValueError
            return number
        except ValueError:
            print("Error: Invalid input. Please enter a positive integer.")


print("Valid positive integer entered:", get_positive_integer())

Enter a positive integer:  -1

Error: Invalid input. Please enter a positive integer.

Enter a positive integer:  -2

Error: Invalid input. Please enter a positive integer.

Enter a positive integer:  0

Error: Invalid input. Please enter a positive integer.

Enter a positive integer:  1

Valid positive integer entered: 1

## 41. Index Error

In [86]:
numbers = []
for i in range(10):
    numbers.append(i)

def access_list(numbers):
    try:
        index = int(input("Enter an index to access: "))
        print("Value at index", index, "is", numbers[index])
    except IndexError:
        print("Error: Index out of range. Please enter a valid index.")

print(numbers)
access_list(numbers)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Enter an index to access:  10

Error: Index out of range. Please enter a valid index.

# numpy section

In [89]:
import numpy as np

## 42. Array Creation

In [93]:
array = np.zeros((3, 3), dtype=np.uint8)
print("Array:", array, sep="\n")

Array:
[[0 0 0]
 [0 0 0]
 [0 0 0]]

## 43. Array Operations

In [100]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

result = array1 + array2

print("Array 1:")
print(array1, "\n")

print("Array 2:")
print(array2, "\n")

print("Result of element-wise addition:")
print(result)

Array 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array 2:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Result of element-wise addition:
[[11 22 33]
 [44 55 66]
 [77 88 99]]

## 44. Array Indexing and Slicing

In [98]:
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

subarray = array[:2, :2]

print("Array:")
print(array, "\n")

print("2x2 Subarray:")
print(subarray)

Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

2x2 Subarray:
[[1 2]
 [5 6]]

## 45. Array Shape and Reshaping

In [101]:
array = np.array([1, 2, 3, 4, 5, 6])

reshaped_array = array.reshape(2, 3)

print("Original Array:")
print(array, "\n")

print("Reshaped Array (2x3):")
print(reshaped_array)

Original Array:
[1 2 3 4 5 6]

Reshaped Array (2x3):
[[1 2 3]
 [4 5 6]]

## 46. Array Aggregation

In [103]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

column_means = np.mean(array, axis=0)

print("Array:")
print(array, "\n")

print("Mean of each column:")
print(column_means)

Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Mean of each column:
[4. 5. 6.]

## 47. Array Broadcasting

In [104]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

array2 = np.array([2, 3, 4])

result = array1 * array2

print("Array 1:")
print(array1, "\n")

print("Array 2:")
print(array2, "\n")

print("Result of element-wise multiplication:")
print(result)

Array 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array 2:
[2 3 4]

Result of element-wise multiplication:
[[ 2  6 12]
 [ 8 15 24]
 [14 24 36]]

# pandas section

In [105]:
import pandas as pd

## 48. DataFrame Creation

In [111]:
# method 1: create a dictionary and convert it to DataFrame
# Create a dictionary with column names and data
data = {
    'Name': ['Jafar', 'Taghi', 'Mammad', 'Ali'],
    'Age': [25, 30, 28, 32],
    'Country': ['USA', 'Canada', 'UK', 'Australia']
}

# Create a DataFrame from the dictionary
df = pd.DataFrame(data)
df

     Name  Age    Country
0   Jafar   25        USA
1   Taghi   30     Canada
2  Mammad   28         UK
3     Ali   32  Australia

In [112]:
# Method 2: Read data from csv into DataFrame and convert to dict and then return to DataFrame
# Load the dataset from a CSV file
df = pd.read_csv('cancer.csv')

# Convert the DataFrame to a dictionary
data_dict = df.to_dict()

# Create a DataFrame from the dictionary
df = pd.DataFrame(data_dict)
df

,State,Total.Rate,Total.Number,Total.Population,Rates.Age.< 18,Rates.Age.18-45,Rates.Age.45-64,Rates.Age.> 64,Rates.Age and Sex.< 18.Female,Rates.Age and Sex.< 18.Male,...,Types.Lung.Age and Sex.Male.45 - 64,Types.Lung.Age and Sex.Female.> 64,Types.Lung.Age and Sex.Male.> 64,Types.Lung.Race.White,Types.Lung.Race.White non-Hispanic,Types.Lung.Race.Black,Types.Lung.Race.Black non-Hispanic,Types.Lung.Race.Asian,Types.Lung.Race.Indigenous,Types.Lung.Race.Hispanic
0,Alabama,214.2,71529.0,33387205.0,2.0,18.5,244.7,1017.8,2.0,2.1,...,102.9,221.7,457.4,59.9,60.4,52.6,52.8,23.0,22.9,14.8
1,Alaska,128.1,6361.0,4966180.0,1.7,11.8,170.9,965.2,0.0,0.0,...,50.3,268.3,335.0,48.7,49.5,45.6,47.9,33.0,74.4,0.0
2,Arizona,165.6,74286.0,44845598.0,2.5,13.6,173.6,840.2,2.6,2.5,...,47.0,191.9,275.8,39.5,42.2,38.2,40.4,21.3,11.1,21.6
3,Arkansas,223.9,45627.0,20382448.0,2.3,17.6,250.1,1048.3,2.6,2.0,...,106.5,248.7,484.7,63.4,64.2,62.9,63.0,18.1,16.2,14.6
4,California,150.9,393980.0,261135696.0,2.6,13.7,163.7,902.4,2.4,2.8,...,36.8,192.5,269.0,37.2,42.6,46.5,48.6,25.8,18.4,18.3
5,Colorado,139.0,49035.0,35267734.0,1.9,11.7,149.6,849.4,1.9,1.9,...,34.0,183.0,242.6,34.1,35.0,40.4,41.5,22.8,22.3,25.6
6,Connecticut,190.5,47567.0,24975889.0,1.6,13.6,163.6,971.2,1.6,1.7,...,47.2,222.2,301.1,42.2,43.2,38.4,40.4,20.8,0.0,20.3
7,Delaware,210.2,13233.0,6295263.0,2.2,16.0,217.5,993.3,0.0,0.0,...,74.9,253.7,369.1,55.0,55.7,49.3,49.8,23.7,0.0,15.5
8,District of Columbia,182.1,7730.0,4245359.0,0.0,12.4,251.8,1028.6,0.0,0.0,...,71.3,193.0,303.2,27.3,27.6,53.6,54.2,0.0,0.0,18.8
9,Florida,219.2,289905.0,132277071.0,2.1,15.9,206.9,901.2,2.0,2.2,...,72.0,215.8,329.0,48.0,52.5,38.1,39.5,19.8,21.0,24.0
10,Georgia,159.4,108222.0,67890652.0,2.2,15.7,205.6,932.2,2.0,2.3,...,74.0,210.9,383.3,52.4,53.7,45.1,45.4,19.1,0.0,10.6
11,Hawaii,166.0,15812.0,9526083.0,2.5,14.9,171.1,787.8,2.2,2.8,...,44.0,153.0,269.3,36.0,37.2,39.6,43.0,32.6,0.0,35.2
12,Idaho,162.1,17756.0,10954295.0,1.9,13.5,168.8,912.2,2.1,1.8,...,42.4,204.1,278.2,39.2,39.9,0.0,0.0,0.0,28.1,19.8
13,Illinois,189.2,169730.0,89696961.0,2.3,14.6,198.6,1037.9,2.0,2.5,...,63.4,240.9,370.7,49.5,51.8,60.1,60.3,21.4,12.6,17.5
14,Indiana,202.7,91978.0,45372690.0,2.4,16.3,218.2,1059.7,2.3,2.5,...,83.6,252.7,434.1,57.6,58.3,64.3,64.6,18.2,0.0,14.6
15,Iowa,210.3,44835.0,21322082.0,2.1,14.7,195.9,1018.1,1.7,2.5,...,69.3,217.6,367.3,48.2,48.6,66.0,66.7,24.6,0.0,18.1
16,Kansas,188.9,37644.0,19928783.0,2.7,14.0,194.4,999.6,2.5,2.8,...,66.0,226.4,368.3,48.0,48.8,59.9,60.8,30.0,81.7,23.8
17,Kentucky,226.3,68675.0,30348057.0,2.2,18.4,256.3,1110.2,1.8,2.7,...,112.6,298.3,519.1,71.5,71.9,73.2,73.6,25.9,0.0,22.0
18,Louisiana,202.9,64194.0,31638386.0,2.3,17.8,246.4,1053.3,1.9,2.7,...,92.2,239.1,432.5,56.2,57.5,61.6,62.0,31.4,24.2,12.8
19,Maine,239.1,22240.0,9301182.0,2.4,15.2,204.7,1061.8,2.4,2.4,...,74.9,259.1,388.1,54.7,54.6,0.0,0.0,0.0,45.1,0.0
20,Maryland,179.3,72603.0,40483979.0,2.0,15.2,189.1,977.5,1.7,2.2,...,58.3,231.0,331.3,47.2,48.5,47.0,47.5,19.8,16.6,10.8
21,Massachusetts,197.8,90756.0,45892272.0,2.1,13.3,177.8,1028.6,2.0,2.2,...,53.3,243.8,340.0,47.9,48.8,34.1,38.1,25.5,15.8,18.5
22,Michigan,205.3,142458.0,69388573.0,2.3,16.4,209.3,1016.3,2.1,2.5,...,71.8,244.7,372.6,51.3,51.7,59.3,59.4,18.7,65.2,29.8
23,Minnesota,178.4,66328.0,37183729.0,2.1,12.9,167.8,983.7,2.0,2.3,...,47.6,212.0,305.6,41.7,42.0,40.3,40.7,21.7,83.8,16.0
24,Mississippi,211.4,43874.0,20756872.0,2.4,19.5,263.9,1049.1,2.2,2.5,...,106.6,223.7,496.4,61.8,62.3,60.1,60.4,33.9,0.0,12.6
25,Missouri,211.2,88348.0,41838390.0,2.3,16.3,221.0,1030.8,2.2,2.4,...,83.1,257.3,419.5,57.1,57.6,60.2,60.5,21.0,27.7,18.5
26,Montana,196.1,13593.0,6933023.0,2.4,11.8,175.4,939.1,0.0,2.5,...,46.9,233.3,299.3,42.6,42.2,0.0,0.0,0.0,59.8,25.6
27,Nebraska,187.5,23977.0,12785524.0,2.7,13.1,179.8,999.5,2.4,3.0,...,54.4,210.8,348.8,44.2,44.8,62.7,64.0,26.6,54.8,18.1
28,Nevada,167.9,31758.0,18912307.0,1.9,13.4,183.7,944.2,1.8,2.1,...,52.0,263.7,325.9,52.1,56.0,44.7,46.1,23.4,27.8,20.4
29,New Hampshire,197.9,18256.0,9223389.0,2.2,14.7,175.2,1009.2,2.9,0.0,...,53.6,246.0,336.8,48.5,48.7,32.6,0.0,0.0,0.0,0.0
30,New Jersey,189.9,116836.0,61521555.0,2.1,14.4,174.8,999.6,1.9,2.2,...,48.5,216.6,317.5,43.9,46.4,42.8,45.4,17.7,12.0,17.9
31,New Mexico,163.2,23425.0,14349762.0,2.2,13.9,167.3,845.0,2.0,2.5,...,35.0,171.5,250.3,35.1,39.3,42.9,47.2,20.2,8.9,26.3
32,New York,183.2,248572.0,135716524.0,2.4,14.3,182.4,942.9,2.2,2.6,...,53.7,208.3,309.1,44.7,46.7,35.6,39.2,23.3,13.8,21.0
33,North Carolina,188.7,125783.0,66669069.0,2.0,15.8,212.6,963.3,1.8,2.2,...,81.6,220.8,409.4,53.4,54.3,51.8,52.2,22.7,50.4,11.3
34,North Dakota,189.1,8990.0,4754903.0,2.1,10.0,165.4,981.7,0.0,0.0,...,45.6,185.6,342.6,39.8,39.7,0.0,0.0,0.0,87.5,0.0
35,Ohio,217.8,175847.0,80741243.0,2.0,16.9,220.2,1061.6,1.9,2.0,...,80.3,250.6,407.9,54.8,55.1,62.9,63.3,25.4,21.5,18.5
36,Oklahoma,209.4,54930.0,26229144.0,2.4,16.3,238.9,1040.5,1.9,2.9,...,88.7,256.6,436.7,59.4,60.5,59.7,60.1,32.1,57.3,19.8
37,Oregon,199.1,53430.0,26832116.0,2.4,13.4,191.3,1001.4,2.2,2.5,...,53.4,250.7,329.6,47.2,48.0,55.3,57.1,29.9,37.2,20.5
38,Pennsylvania,227.7,202230.0,88825682.0,2.2,15.7,204.1,1057.3,2.1,2.4,...,66.5,225.8,373.4,48.1,48.4,60.2,61.4,23.4,20.9,19.8
39,Rhode Island,211.2,15570.0,7371636.0,1.4,13.3,190.3,1052.1,0.0,0.0,...,64.2,247.9,379.8,51.7,53.0,33.7,39.5,25.5,0.0,15.0
40,South Carolina,202.6,65561.0,32366134.0,2.1,17.0,235.5,957.1,2.1,2.2,...,91.3,212.9,393.9,54.3,54.8,49.4,48.7,23.4,40.8,19.2
41,South Dakota,196.2,11212.0,5714307.0,2.3,12.4,175.7,1007.1,0.0,3.2,...,56.4,206.2,361.2,43.9,44.2,0.0,0.0,0.0,70.3,0.0
42,Tennessee,213.1,94678.0,44430836.0,2.4,17.7,245.2,1032.1,2.3,2.5,...,101.0,248.4,461.5,61.5,62.1,62.1,62.5,25.8,21.3,8.8
43,Texas,145.8,257000.0,176270421.0,2.5,14.7,186.6,904.8,2.3,2.7,...,54.3,200.0,331.9,42.9,50.1,54.1,54.9,22.2,9.0,20.8
44,Utah,98.5,19022.0,19321462.0,1.9,10.9,132.3,735.8,1.6,2.2,...,26.0,92.7,153.2,20.4,20.6,31.1,35.0,18.5,17.8,17.3
45,Vermont,211.6,9261.0,4377262.0,2.2,16.2,188.1,1002.8,0.0,0.0,...,59.7,243.6,337.0,49.7,49.8,0.0,0.0,0.0,0.0,0.0
46,Virginia,177.1,99278.0,56054333.0,2.2,14.5,189.3,971.0,1.9,2.5,...,63.4,226.2,359.8,48.7,49.5,52.6,52.7,23.7,17.0,15.3
47,Washington,175.9,82864.0,47114240.0,2.3,13.2,177.5,982.0,2.3,2.3,...,49.4,241.1,317.9,46.3,47.2,46.6,47.8,29.0,43.4,18.2
48,West Virginia,254.6,32950.0,12940212.0,2.5,20.3,254.0,1068.9,2.2,2.7,...,100.2,264.7,445.8,62.7,63.0,59.1,59.6,0.0,0.0,0.0
49,Wisconsin,197.5,78578.0,39788899.0,2.2,13.8,181.2,1028.1,2.1,2.2,...,55.0,223.1,339.9,44.6,45.1,70.6,71.7,20.6,79.0,16.1
50,Wyoming,167.9,6603.0,3931624.0,0.0,11.8,168.3,924.9,0.0,0.0,...,39.0,205.6,290.4,40.0,40.8,0.0,0.0,0.0,55.2,21.4

## 49. Data Exploration

In [114]:
df = pd.read_csv('cancer.csv')
print(df.head())

        State  Total.Rate  Total.Number  Total.Population  Rates.Age.< 18  \
0     Alabama       214.2       71529.0        33387205.0             2.0
1      Alaska       128.1        6361.0         4966180.0             1.7
2     Arizona       165.6       74286.0        44845598.0             2.5
3    Arkansas       223.9       45627.0        20382448.0             2.3
4  California       150.9      393980.0       261135696.0             2.6

   Rates.Age.18-45  Rates.Age.45-64  Rates.Age.> 64  \
0             18.5            244.7          1017.8
1             11.8            170.9           965.2
2             13.6            173.6           840.2
3             17.6            250.1          1048.3
4             13.7            163.7           902.4

   Rates.Age and Sex.< 18.Female  Rates.Age and Sex.< 18.Male  ...  \
0                            2.0                          2.1  ...
1                            0.0                          0.0  ...
2                            2.6                          2.5  ...
3                            2.6                          2.0  ...
4                            2.4                          2.8  ...

   Types.Lung.Age and Sex.Male.45 - 64  Types.Lung.Age and Sex.Female.> 64  \
0                                102.9                               221.7
1                                 50.3                               268.3
2                                 47.0                               191.9
3                                106.5                               248.7
4                                 36.8                               192.5

   Types.Lung.Age and Sex.Male.> 64  Types.Lung.Race.White  \
0                             457.4                   59.9
1                             335.0                   48.7
2                             275.8                   39.5
3                             484.7                   63.4
4                             269.0                   37.2

   Types.Lung.Race.White non-Hispanic  Types.Lung.Race.Black  \
0                                60.4                   52.6
1                                49.5                   45.6
2                                42.2                   38.2
3                                64.2                   62.9
4                                42.6                   46.5

   Types.Lung.Race.Black non-Hispanic  Types.Lung.Race.Asian  \
0                                52.8                   23.0
1                                47.9                   33.0
2                                40.4                   21.3
3                                63.0                   18.1
4                                48.6                   25.8

   Types.Lung.Race.Indigenous  Types.Lung.Race.Hispanic
0                        22.9                      14.8
1                        74.4                       0.0
2                        11.1                      21.6
3                        16.2                      14.6
4                        18.4                      18.3

[5 rows x 75 columns]

## 50. Data Selection and Indexing

In [116]:
df = pd.read_csv('cancer.csv')

# Select State column
column = df['State']

print(column)

0                  Alabama
1                   Alaska
2                  Arizona
3                 Arkansas
4               California
5                 Colorado
6              Connecticut
7                 Delaware
8     District of Columbia
9                  Florida
10                 Georgia
11                  Hawaii
12                   Idaho
13                Illinois
14                 Indiana
15                    Iowa
16                  Kansas
17                Kentucky
18               Louisiana
19                   Maine
20                Maryland
21           Massachusetts
22                Michigan
23               Minnesota
24             Mississippi
25                Missouri
26                 Montana
27                Nebraska
28                  Nevada
29           New Hampshire
30              New Jersey
31              New Mexico
32                New York
33          North Carolina
34            North Dakota
35                    Ohio
36                Oklahoma
37                  Oregon
38            Pennsylvania
39            Rhode Island
40          South Carolina
41            South Dakota
42               Tennessee
43                   Texas
44                    Utah
45                 Vermont
46                Virginia
47              Washington
48           West Virginia
49               Wisconsin
50                 Wyoming
Name: State, dtype: object

## 51. Data Manipulation

In [117]:
df = pd.read_csv('cancer.csv')
sorted_df = df.sort_values('State')
print(sorted_df)

                   State  Total.Rate  Total.Number  Total.Population  \
0                Alabama       214.2       71529.0        33387205.0
1                 Alaska       128.1        6361.0         4966180.0
2                Arizona       165.6       74286.0        44845598.0
3               Arkansas       223.9       45627.0        20382448.0
4             California       150.9      393980.0       261135696.0
5               Colorado       139.0       49035.0        35267734.0
6            Connecticut       190.5       47567.0        24975889.0
7               Delaware       210.2       13233.0         6295263.0
8   District of Columbia       182.1        7730.0         4245359.0
9                Florida       219.2      289905.0       132277071.0
10               Georgia       159.4      108222.0        67890652.0
11                Hawaii       166.0       15812.0         9526083.0
12                 Idaho       162.1       17756.0        10954295.0
13              Illinois       189.2      169730.0        89696961.0
14               Indiana       202.7       91978.0        45372690.0
15                  Iowa       210.3       44835.0        21322082.0
16                Kansas       188.9       37644.0        19928783.0
17              Kentucky       226.3       68675.0        30348057.0
18             Louisiana       202.9       64194.0        31638386.0
19                 Maine       239.1       22240.0         9301182.0
20              Maryland       179.3       72603.0        40483979.0
21         Massachusetts       197.8       90756.0        45892272.0
22              Michigan       205.3      142458.0        69388573.0
23             Minnesota       178.4       66328.0        37183729.0
24           Mississippi       211.4       43874.0        20756872.0
25              Missouri       211.2       88348.0        41838390.0
26               Montana       196.1       13593.0         6933023.0
27              Nebraska       187.5       23977.0        12785524.0
28                Nevada       167.9       31758.0        18912307.0
29         New Hampshire       197.9       18256.0         9223389.0
30            New Jersey       189.9      116836.0        61521555.0
31            New Mexico       163.2       23425.0        14349762.0
32              New York       183.2      248572.0       135716524.0
33        North Carolina       188.7      125783.0        66669069.0
34          North Dakota       189.1        8990.0         4754903.0
35                  Ohio       217.8      175847.0        80741243.0
36              Oklahoma       209.4       54930.0        26229144.0
37                Oregon       199.1       53430.0        26832116.0
38          Pennsylvania       227.7      202230.0        88825682.0
39          Rhode Island       211.2       15570.0         7371636.0
40        South Carolina       202.6       65561.0        32366134.0
41          South Dakota       196.2       11212.0         5714307.0
42             Tennessee       213.1       94678.0        44430836.0
43                 Texas       145.8      257000.0       176270421.0
44                  Utah        98.5       19022.0        19321462.0
45               Vermont       211.6        9261.0         4377262.0
46              Virginia       177.1       99278.0        56054333.0
47            Washington       175.9       82864.0        47114240.0
48         West Virginia       254.6       32950.0        12940212.0
49             Wisconsin       197.5       78578.0        39788899.0
50               Wyoming       167.9        6603.0         3931624.0

    Rates.Age.< 18  Rates.Age.18-45  Rates.Age.45-64  Rates.Age.> 64  \
0              2.0             18.5            244.7          1017.8
1              1.7             11.8            170.9           965.2
2              2.5             13.6            173.6           840.2
3              2.3             17.6            250.1          1048.3
4              2.6             13.7            163.7           902.4
5              1.9             11.7            149.6           849.4
6              1.6             13.6            163.6           971.2
7              2.2             16.0            217.5           993.3
8              0.0             12.4            251.8          1028.6
9              2.1             15.9            206.9           901.2
10             2.2             15.7            205.6           932.2
11             2.5             14.9            171.1           787.8
12             1.9             13.5            168.8           912.2
13             2.3             14.6            198.6          1037.9
14             2.4             16.3            218.2          1059.7
15             2.1             14.7            195.9          1018.1
16             2.7             14.0            194.4           999.6
17             2.2             18.4            256.3          1110.2
18             2.3             17.8            246.4          1053.3
19             2.4             15.2            204.7          1061.8
20             2.0             15.2            189.1           977.5
21             2.1             13.3            177.8          1028.6
22             2.3             16.4            209.3          1016.3
23             2.1             12.9            167.8           983.7
24             2.4             19.5            263.9          1049.1
25             2.3             16.3            221.0          1030.8
26             2.4             11.8            175.4           939.1
27             2.7             13.1            179.8           999.5
28             1.9             13.4            183.7           944.2
29             2.2             14.7            175.2          1009.2
30             2.1             14.4            174.8           999.6
31             2.2             13.9            167.3           845.0
32             2.4             14.3            182.4           942.9
33             2.0             15.8            212.6           963.3
34             2.1             10.0            165.4           981.7
35             2.0             16.9            220.2          1061.6
36             2.4             16.3            238.9          1040.5
37             2.4             13.4            191.3          1001.4
38             2.2             15.7            204.1          1057.3
39             1.4             13.3            190.3          1052.1
40             2.1             17.0            235.5           957.1
41             2.3             12.4            175.7          1007.1
42             2.4             17.7            245.2          1032.1
43             2.5             14.7            186.6           904.8
44             1.9             10.9            132.3           735.8
45             2.2             16.2            188.1          1002.8
46             2.2             14.5            189.3           971.0
47             2.3             13.2            177.5           982.0
48             2.5             20.3            254.0          1068.9
49             2.2             13.8            181.2          1028.1
50             0.0             11.8            168.3           924.9

    Rates.Age and Sex.< 18.Female  Rates.Age and Sex.< 18.Male  ...  \
0                             2.0                          2.1  ...
1                             0.0                          0.0  ...
2                             2.6                          2.5  ...
3                             2.6                          2.0  ...
4                             2.4                          2.8  ...
5                             1.9                          1.9  ...
6                             1.6                          1.7  ...
7                             0.0                          0.0  ...
8                             0.0                          0.0  ...
9                             2.0                          2.2  ...
10                            2.0                          2.3  ...
11                            2.2                          2.8  ...
12                            2.1                          1.8  ...
13                            2.0                          2.5  ...
14                            2.3                          2.5  ...
15                            1.7                          2.5  ...
16                            2.5                          2.8  ...
17                            1.8                          2.7  ...
18                            1.9                          2.7  ...
19                            2.4                          2.4  ...
20                            1.7                          2.2  ...
21                            2.0                          2.2  ...
22                            2.1                          2.5  ...
23                            2.0                          2.3  ...
24                            2.2                          2.5  ...
25                            2.2                          2.4  ...
26                            0.0                          2.5  ...
27                            2.4                          3.0  ...
28                            1.8                          2.1  ...
29                            2.9                          0.0  ...
30                            1.9                          2.2  ...
31                            2.0                          2.5  ...
32                            2.2                          2.6  ...
33                            1.8                          2.2  ...
34                            0.0                          0.0  ...
35                            1.9                          2.0  ...
36                            1.9                          2.9  ...
37                            2.2                          2.5  ...
38                            2.1                          2.4  ...
39                            0.0                          0.0  ...
40                            2.1                          2.2  ...
41                            0.0                          3.2  ...
42                            2.3                          2.5  ...
43                            2.3                          2.7  ...
44                            1.6                          2.2  ...
45                            0.0                          0.0  ...
46                            1.9                          2.5  ...
47                            2.3                          2.3  ...
48                            2.2                          2.7  ...
49                            2.1                          2.2  ...
50                            0.0                          0.0  ...

    Types.Lung.Age and Sex.Male.45 - 64  Types.Lung.Age and Sex.Female.> 64  \
0                                 102.9                               221.7
1                                  50.3                               268.3
2                                  47.0                               191.9
3                                 106.5                               248.7
4                                  36.8                               192.5
5                                  34.0                               183.0
6                                  47.2                               222.2
7                                  74.9                               253.7
8                                  71.3                               193.0
9                                  72.0                               215.8
10                                 74.0                               210.9
11                                 44.0                               153.0
12                                 42.4                               204.1
13                                 63.4                               240.9
14                                 83.6                               252.7
15                                 69.3                               217.6
16                                 66.0                               226.4
17                                112.6                               298.3
18                                 92.2                               239.1
19                                 74.9                               259.1
20                                 58.3                               231.0
21                                 53.3                               243.8
22                                 71.8                               244.7
23                                 47.6                               212.0
24                                106.6                               223.7
25                                 83.1                               257.3
26                                 46.9                               233.3
27                                 54.4                               210.8
28                                 52.0                               263.7
29                                 53.6                               246.0
30                                 48.5                               216.6
31                                 35.0                               171.5
32                                 53.7                               208.3
33                                 81.6                               220.8
34                                 45.6                               185.6
35                                 80.3                               250.6
36                                 88.7                               256.6
37                                 53.4                               250.7
38                                 66.5                               225.8
39                                 64.2                               247.9
40                                 91.3                               212.9
41                                 56.4                               206.2
42                                101.0                               248.4
43                                 54.3                               200.0
44                                 26.0                                92.7
45                                 59.7                               243.6
46                                 63.4                               226.2
47                                 49.4                               241.1
48                                100.2                               264.7
49                                 55.0                               223.1
50                                 39.0                               205.6

    Types.Lung.Age and Sex.Male.> 64  Types.Lung.Race.White  \
0                              457.4                   59.9
1                              335.0                   48.7
2                              275.8                   39.5
3                              484.7                   63.4
4                              269.0                   37.2
5                              242.6                   34.1
6                              301.1                   42.2
7                              369.1                   55.0
8                              303.2                   27.3
9                              329.0                   48.0
10                             383.3                   52.4
11                             269.3                   36.0
12                             278.2                   39.2
13                             370.7                   49.5
14                             434.1                   57.6
15                             367.3                   48.2
16                             368.3                   48.0
17                             519.1                   71.5
18                             432.5                   56.2
19                             388.1                   54.7
20                             331.3                   47.2
21                             340.0                   47.9
22                             372.6                   51.3
23                             305.6                   41.7
24                             496.4                   61.8
25                             419.5                   57.1
26                             299.3                   42.6
27                             348.8                   44.2
28                             325.9                   52.1
29                             336.8                   48.5
30                             317.5                   43.9
31                             250.3                   35.1
32                             309.1                   44.7
33                             409.4                   53.4
34                             342.6                   39.8
35                             407.9                   54.8
36                             436.7                   59.4
37                             329.6                   47.2
38                             373.4                   48.1
39                             379.8                   51.7
40                             393.9                   54.3
41                             361.2                   43.9
42                             461.5                   61.5
43                             331.9                   42.9
44                             153.2                   20.4
45                             337.0                   49.7
46                             359.8                   48.7
47                             317.9                   46.3
48                             445.8                   62.7
49                             339.9                   44.6
50                             290.4                   40.0

    Types.Lung.Race.White non-Hispanic  Types.Lung.Race.Black  \
0                                 60.4                   52.6
1                                 49.5                   45.6
2                                 42.2                   38.2
3                                 64.2                   62.9
4                                 42.6                   46.5
5                                 35.0                   40.4
6                                 43.2                   38.4
7                                 55.7                   49.3
8                                 27.6                   53.6
9                                 52.5                   38.1
10                                53.7                   45.1
11                                37.2                   39.6
12                                39.9                    0.0
13                                51.8                   60.1
14                                58.3                   64.3
15                                48.6                   66.0
16                                48.8                   59.9
17                                71.9                   73.2
18                                57.5                   61.6
19                                54.6                    0.0
20                                48.5                   47.0
21                                48.8                   34.1
22                                51.7                   59.3
23                                42.0                   40.3
24                                62.3                   60.1
25                                57.6                   60.2
26                                42.2                    0.0
27                                44.8                   62.7
28                                56.0                   44.7
29                                48.7                   32.6
30                                46.4                   42.8
31                                39.3                   42.9
32                                46.7                   35.6
33                                54.3                   51.8

## 52. Missing Data Handling

In [119]:
df = pd.read_csv('cancer.csv')
missing_values = df.isnull()
print(missing_values)

    State  Total.Rate  Total.Number  Total.Population  Rates.Age.< 18  \
0   False       False         False             False           False
1   False       False         False             False           False
2   False       False         False             False           False
3   False       False         False             False           False
4   False       False         False             False           False
5   False       False         False             False           False
6   False       False         False             False           False
7   False       False         False             False           False
8   False       False         False             False           False
9   False       False         False             False           False
10  False       False         False             False           False
11  False       False         False             False           False
12  False       False         False             False           False
13  False       False         False             False           False
14  False       False         False             False           False
15  False       False         False             False           False
16  False       False         False             False           False
17  False       False         False             False           False
18  False       False         False             False           False
19  False       False         False             False           False
20  False       False         False             False           False
21  False       False         False             False           False
22  False       False         False             False           False
23  False       False         False             False           False
24  False       False         False             False           False
25  False       False         False             False           False
26  False       False         False             False           False
27  False       False         False             False           False
28  False       False         False             False           False
29  False       False         False             False           False
30  False       False         False             False           False
31  False       False         False             False           False
32  False       False         False             False           False
33  False       False         False             False           False
34  False       False         False             False           False
35  False       False         False             False           False
36  False       False         False             False           False
37  False       False         False             False           False
38  False       False         False             False           False
39  False       False         False             False           False
40  False       False         False             False           False
41  False       False         False             False           False
42  False       False         False             False           False
43  False       False         False             False           False
44  False       False         False             False           False
45  False       False         False             False           False
46  False       False         False             False           False
47  False       False         False             False           False
48  False       False         False             False           False
49  False       False         False             False           False
50  False       False         False             False           False

    Rates.Age.18-45  Rates.Age.45-64  Rates.Age.> 64  \
0             False            False           False
1             False            False           False
2             False            False           False
3             False            False           False
4             False            False           False
5             False            False           False
6             False            False           False
7             False            False           False
8             False            False           False
9             False            False           False
10            False            False           False
11            False            False           False
12            False            False           False
13            False            False           False
14            False            False           False
15            False            False           False
16            False            False           False
17            False            False           False
18            False            False           False
19            False            False           False
20            False            False           False
21            False            False           False
22            False            False           False
23            False            False           False
24            False            False           False
25            False            False           False
26            False            False           False
27            False            False           False
28            False            False           False
29            False            False           False
30            False            False           False
31            False            False           False
32            False            False           False
33            False            False           False
34            False            False           False
35            False            False           False
36            False            False           False
37            False            False           False
38            False            False           False
39            False            False           False
40            False            False           False
41            False            False           False
42            False            False           False
43            False            False           False
44            False            False           False
45            False            False           False
46            False            False           False
47            False            False           False
48            False            False           False
49            False            False           False
50            False            False           False

    Rates.Age and Sex.< 18.Female  Rates.Age and Sex.< 18.Male  ...  \
0                           False                        False  ...
1                           False                        False  ...
2                           False                        False  ...
3                           False                        False  ...
4                           False                        False  ...
5                           False                        False  ...
6                           False                        False  ...
7                           False                        False  ...
8                           False                        False  ...
9                           False                        False  ...
10                          False                        False  ...
11                          False                        False  ...
12                          False                        False  ...
13                          False                        False  ...
14                          False                        False  ...
15                          False                        False  ...
16                          False                        False  ...
17                          False                        False  ...
18                          False                        False  ...
19                          False                        False  ...
20                          False                        False  ...
21                          False                        False  ...
22                          False                        False  ...
23                          False                        False  ...
24                          False                        False  ...
25                          False                        False  ...
26                          False                        False  ...
27                          False                        False  ...
28                          False                        False  ...
29                          False                        False  ...
30                          False                        False  ...
31                          False                        False  ...
32                          False                        False  ...
33                          False                        False  ...
34                          False                        False  ...
35                          False                        False  ...
36                          False                        False  ...
37                          False                        False  ...
38                          False                        False  ...
39                          False                        False  ...
40                          False                        False  ...
41                          False                        False  ...
42                          False                        False  ...
43                          False                        False  ...
44                          False                        False  ...
45                          False                        False  ...
46                          False                        False  ...
47                          False                        False  ...
48                          False                        False  ...
49                          False                        False  ...
50                          False                        False  ...

    Types.Lung.Age and Sex.Male.45 - 64  Types.Lung.Age and Sex.Female.> 64  \
0                                 False                               False
1                                 False                               False
2                                 False                               False
3                                 False                               False
4                                 False                               False
5                                 False                               False
6                                 False                               False
7                                 False                               False
8                                 False                               False
9                                 False                               False
10                                False                               False
11                                False                               False
12                                False                               False
13                                False                               False
14                                False                               False
15                                False                               False
16                                False                               False
17                                False                               False
18                                False                               False
19                                False                               False
20                                False                               False
21                                False                               False
22                                False                               False
23                                False                               False
24                                False                               False
25                                False                               False
26                                False                               False
27                                False                               False
28                                False                               False
29                                False                               False
30                                False                               False
31                                False                               False
32                                False                               False
33                                False                               False
34                                False                               False
35                                False                               False
36                                False                               False
37                                False                               False
38                                False                               False
39                                False                               False
40                                False                               False
41                                False                               False
42                                False                               False
43                                False                               False
44                                False                               False
45                                False                               False
46                                False                               False
47                                False                               False
48                                False                               False
49                                False                               False
50                                False                               False

    Types.Lung.Age and Sex.Male.> 64  Types.Lung.Race.White  \
0                              False                  False
1                              False                  False
2                              False                  False
3                              False                  False
4                              False                  False
5                              False                  False
6                              False                  False
7                              False                  False
8                              False                  False
9                              False                  False
10                             False                  False
11                             False                  False
12                             False                  False
13                             False                  False
14                             False                  False
15                             False                  False
16                             False                  False
17                             False                  False
18                             False                  False
19                             False                  False
20                             False                  False
21                             False                  False
22                             False                  False
23                             False                  False
24                             False                  False
25                             False                  False
26                             False                  False
27                             False                  False
28                             False                  False
29                             False                  False
30                             False                  False
31                             False                  False
32                             False                  False
33                             False                  False
34                             False                  False
35                             False                  False
36                             False                  False
37                             False                  False
38                             False                  False
39                             False                  False
40                             False                  False
41                             False                  False
42                             False                  False
43                             False                  False
44                             False                  False
45                             False                  False
46                             False                  False
47                             False                  False
48                             False                  False
49                             False                  False
50                             False                  False

    Types.Lung.Race.White non-Hispanic  Types.Lung.Race.Black  \
0                                False                  False
1                                False                  False
2                                False                  False
3                                False                  False
4                                False                  False
5                                False                  False
6                                False                  False
7                                False                  False
8                                False                  False
9                                False                  False
10                               False                  False
11                               False                  False
12                               False                  False
13                               False                  False
14                               False                  False
15                               False                  False
16                               False                  False
17                               False                  False
18                               False                  False
19                               False                  False
20                               False                  False
21                               False                  False
22                               False                  False
23                               False                  False
24                               False                  False
25                               False                  False
26                               False                  False
27                               False                  False
28                               False                  False
29                               False                  False
30                               False                  False
31                               False                  False
32                               False                  False
33                               False                  False
34                               False                  False
35                               False                  False
36                               False                  False
37                               False                  False
38                               False                  False
39                               False                  False
40                               False                  False
41                               False                  False
42                               False                  False
43                               False                  False
44                               False                  False
45                               False                  False

## 53. Grouping and Aggregation

In [124]:
df = pd.read_csv('cancer.csv')

# Group the DataFrame by a State column and calculate the mean, sum, or count of Total.Number
grouped_data = df.groupby('State')['Total.Number'].agg(['mean', 'sum', 'count'])

print(grouped_data)

                          mean       sum  count
State
Alabama                71529.0   71529.0      1
Alaska                  6361.0    6361.0      1
Arizona                74286.0   74286.0      1
Arkansas               45627.0   45627.0      1
California            393980.0  393980.0      1
Colorado               49035.0   49035.0      1
Connecticut            47567.0   47567.0      1
Delaware               13233.0   13233.0      1
District of Columbia    7730.0    7730.0      1
Florida               289905.0  289905.0      1
Georgia               108222.0  108222.0      1
Hawaii                 15812.0   15812.0      1
Idaho                  17756.0   17756.0      1
Illinois              169730.0  169730.0      1
Indiana                91978.0   91978.0      1
Iowa                   44835.0   44835.0      1
Kansas                 37644.0   37644.0      1
Kentucky               68675.0   68675.0      1
Louisiana              64194.0   64194.0      1
Maine                  22240.0   22240.0      1
Maryland               72603.0   72603.0      1
Massachusetts          90756.0   90756.0      1
Michigan              142458.0  142458.0      1
Minnesota              66328.0   66328.0      1
Mississippi            43874.0   43874.0      1
Missouri               88348.0   88348.0      1
Montana                13593.0   13593.0      1
Nebraska               23977.0   23977.0      1
Nevada                 31758.0   31758.0      1
New Hampshire          18256.0   18256.0      1
New Jersey            116836.0  116836.0      1
New Mexico             23425.0   23425.0      1
New York              248572.0  248572.0      1
North Carolina        125783.0  125783.0      1
North Dakota            8990.0    8990.0      1
Ohio                  175847.0  175847.0      1
Oklahoma               54930.0   54930.0      1
Oregon                 53430.0   53430.0      1
Pennsylvania          202230.0  202230.0      1
Rhode Island           15570.0   15570.0      1
South Carolina         65561.0   65561.0      1
South Dakota           11212.0   11212.0      1
Tennessee              94678.0   94678.0      1
Texas                 257000.0  257000.0      1
Utah                   19022.0   19022.0      1
Vermont                 9261.0    9261.0      1
Virginia               99278.0   99278.0      1
Washington             82864.0   82864.0      1
West Virginia          32950.0   32950.0      1
Wisconsin              78578.0   78578.0      1
Wyoming                 6603.0    6603.0      1